# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3b879d9f12b812a4d1bcaad5ca356d8"
name = "instagram"
application_url = "https://vercal.websterzone.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers-data-request"
  compliance_topics = ["customers/data_request"]
  
  [[webhooks.subscriptions]]
  uri = "/webhooks/customers-redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop-redact"
  compliance_topics = ["shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [ "https://vercal.websterzone.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
